### PR TITLE
Allow functions to not have a variable declaration typedef

### PR DESCRIPTION
**Pull request by na-ji**
Fix issue #11

### CODE REVIEW

**Review by ccoeurderoy — CHANGES_REQUESTED** [review]
Could you patch the version please? Unfortunately, this node module has not been implemented with semantic-release yet

**Review by pierreneveu — APPROVED** [review]

**Comment by na-ji** [comment]
Shouldn't the version patch be in a separate commit? Using `npm version` command?

**Comment by ccoeurderoy** [comment]
Yes in a separate commit

**Comment by na-ji** [comment]
I mean after the merge

**Comment by ccoeurderoy** [comment]
Normally yes, but in this repo, the `npm publish` is done after the merge. So it will fail if the version has not changed

**Review by ccoeurderoy — APPROVED** [review]
👍

**Comment by ccoeurderoy** [comment]
Waiting for one more approval to merge this 😬 @diephil ?

**Review by fabong — APPROVED** [review]

**Pull request merged**
